# Build settings
title: System Administrator Musings
description: >
  A site by a Client Platform Engineer at Spotify
  that documents the fun things that have been encountered along the fun
  journey of managing macOS and iOS devices.
permalink: ':title/'
remote_theme: artemsheludko/flexible-jekyll
url: https://www.joshua-d-miller.com   # with the https protocol
enforce_ssl: www.joshua-d-miller.com   # without any protocol

# Author settings
author: Joshua D. Miller
author-img: author.jpg
about-author: >
  Husband, Father, and avid administrator of devices
  at Spotify.
social-email: josh.miller@outlook.com
social-github: https://github.com/joshua-d-miller
social-twitter: joshuadmiller_
social-linkedin: http://linkedin.com/in/millerjoshuad

# Disqus and Tracker
analytics: UA-85695157-1
disqus_identifier: joshuadmiller

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-auto-image
  - jemoji
  - jekyll-remote-theme

timezone: America/New_York

paginate: 10
paginate_path: "/page/:num/"

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
